### ISSUE TITLE
fonction emplacement

### ISSUE THREAD

**Issue by capitainekurck** [lcapdecomme/vins#22]
j'ai fait la mise a jour vers la V5 j'ai fait l'update de la BDD mais il n'y a pas la fonction emplacement.
j'ai toujours connecté ou pas le champs région.

lorsque, une fois connecté, je vais dans le formulaire emplacement il est vide alors q'il devrait en avoir 3. Si j’essaie de saisir un nouvel emplacement a partir du formulaire  mes emplacement et que je clique sur sauver il ne se passe rien.

**Comment by lcapdecomme** [comment]
Bonjour, mes réponses :

_j'ai fait la mise a jour vers la V5 j'ai fait l'update de la BDD mais il n'y a pas la fonction emplacement._
=> La gestion des emplacements se situe dans le menu de l'utilisateur connecté

_j'ai toujours connecté ou pas le champs région._
=> Tant qu'il n'y a pas d'emplacement, la page principale affiche la région

lorsque, une fois connecté, je vais dans le formulaire emplacement il est vide alors q'il devrait en avoir 3. 
=> Vous avez inséré trois emplacements directement en base ? 

_Si j’essaie de saisir un nouvel emplacement a partir du formulaire mes emplacement et que je clique sur sauver il ne se passe rien._
=> Peut-être un problème de cache de votre navigateur ? essayer de faire CTRL-F5 sur la page ou de vider l'historique 

Je viens de télécharger le source de la v0.5 (https://github.com/lcapdecomme/vins/releases/tag/v0.5) et tout me semble ok sur mon poste.

**Comment by capitainekurck** [comment]
_j'ai fait la mise a jour vers la V5 j'ai fait l'update de la BDD mais il n'y a pas la fonction emplacement.
=> La gestion des emplacements se situe dans le menu de l'utilisateur connecté_
oui je me suis mal exprimé, je voulais dire que je sois connecté ou pas j'ai le champ région et pas emplacement dans la liste des vins

_lorsque, une fois connecté, je vais dans le formulaire emplacement il est vide alors q'il devrait en avoir 3.
=> Vous avez inséré trois emplacements directement en base ? _
les 3 emplacements sont ceux de l'import de votre base , enfin 2 (gaillac et Toulouse) et j'en ai rajouté 1 (Corbieres) en faisant des tests quand j'ai créé une bouteille. j'ai rien rajouté directement en base sans passer par les formulaires ou l'import de la bdd. les emplacements sont bien dans la table emplacement de la bdd ?

Pour le cache c'est pas ça, je fait une ctrl f5 a chaque fois que je teste. Sinon je viens de faire un test avec les sources de votre lien,  et dans cette version je n'ai plus dans le header la fonction recherche et le bouton de connexion et redevenu bleu et plus vert
![vins-4](https://cloud.githubusercontent.com/assets/23299954/20248352/a2b5d0c6-a9e2-11e6-8a9c-1f0455c9139c.jpg)
![vins-2](https://cloud.githubusercontent.com/assets/23299954/20248354/a2be4634-a9e2-11e6-956f-d1933756665a.jpg)
![vins-3](https://cloud.githubusercontent.com/assets/23299954/20248353/a2ba3328-a9e2-11e6-8fb5-97caca03896d.jpg)

**Comment by lcapdecomme** [comment]
Je vois que votre bd se nomme _**vin**_. Elle se nomme vin**s** (avec un 's') depuis la version v0.2.
Vous devriez supprimer cette base _**vin**_ (sans s) qui ne sert à rien et passer le patch sur la base **_vins_** (avec un s)
Concernant le bouton vert, c'est la prochaine version en cours de développement. 
Je vous conseille d'utiliser uniquement les versions de type 'release', c'est-à-dire les versions que je teste.
La version qui est sur la page principale se nomme **_master_**, c'est-à-dire la branche en cours de développement. Il faut éviter de l'utilser car potentiellement instable.

**Comment by lcapdecomme** [comment]
Et avant de supprimer cette base de données vin (sans s), vérifiez peut-être que vos bouteilles sont bien dans la base de données vins (avec un s)
Si ce n'est pas le cas, il vous faudra exporter les données de l'ancienne base vers la nouvelle.

**Comment by capitainekurck** [comment]
En fait je n'ai pas 2 bases (vin et vins) il n'y en a qu une seule vin sans s. car je cherchais sur le net une applie de gestion de cave et j'ai testé les 2 ou 3 applies que j'ai trouvé mais qui ne correspondaient pas a ce que je voulais.
 J'ai modifié le fichier import SQL pour utiliser la base vin qui existait déjà avec l’utilisateur déjà configuré sous mon mysql. j'ai dropper toutes les anciennes tables avant l'import et mis les bonnes valeurs dans le fichier config\database.php

**Comment by capitainekurck** [comment]
J'ai fait un test avec la version release V5 et j'ai les mêmes symptôme. l'ajout d'emplacement fige lors de la sauvegarde du nouvel emplacement 
Je n'ai jamais de champ emplacement dans la page principale des vins une fois connecté (j'ai toujours régions)
et lors de l'ajout d'un vin je n'ai pas dans le masque de saisie le champ emplacement. le dernier champ est appellation

par contre le champ cépage fonctionne

**Comment by lcapdecomme** [comment]
Ok, j'ai oublié une requete SQL.
Pouvez-vous passer cette requête et refaire un test ? 
**alter table emplacement add id_utilisateur int(10);**

**Comment by capitainekurck** [comment]
oui la c'est mieux mais il faut aussi mettre la valeur d'un id_utilisateur dans ce champs sinon les symptômes sont les même que j'ai décrit plus haut.
par contre la parti gestion des emplacement ne fonctionne pas. on ne peut toujours pas ajouter un emplacement. la fenêtre de saisie apparait bien mais on a beau cliquer sur sauver rien ne se passe. il faut faire annuler. idem pour les bouton modifier et supprimer ( petits carres bleus) rien ne se passe aussi en cliquant dessus.

**Comment by lcapdecomme** [comment]
Je viens de créer un environnement de test et repasser le script de création de la base et le patch v0.5.sql
Il manquait une autre colonne dans la table des utilisateurs
**_alter table utilisateur add nb_vins_affiches int(5);_**
Par contre cela n'explique pas votre problème sur les emplacements car sur mon environnement de test c'est ok.
Pouvez-vous vérifier que sur la table emplacement, la colonne 'id' est bien de type AUTO_INCREMENT ? 
Dans tous les cas, passez cette requette sur votre environnement : 
**_ALTER TABLE `emplacement`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=100;_**

**Comment by capitainekurck** [comment]
J'ai passé les 2 requêtes mais c'est pareil. de toute manière l'index de la table emplacement était bien en auto-incrément.
oui c'est étrange car les bouton de la gestion des bouteilles (modifier supprimer et boire) fonctionne mais pas ceux des emplacement . pourtant vous utiliser un framwork je pense et vous devez appeler les même fonctions.

**Comment by lcapdecomme** [comment]
J'ai poussé une nouvelle version v0.51 qui affiche les erreurs rencontrées.
En espérant qu'on y voit plus clair.
Cette version intègre la recherche dans le champs commentaire.
La release est ici : https://github.com/lcapdecomme/vins/releases/tag/v0.51

**Comment by capitainekurck** [comment]
bonsoir
J'ai installé la V0.51 et ça marche nickel. j'ai re téléchargé la V0.50 et apres install ca ne marche plus
le code ne doit pas etre exactement pareil. il y a un bug dans la V0.50 qu'il n'y a plus dans la V0.51

**Comment by lcapdecomme** [comment]
parfait !
