### ISSUE TITLE
saisie des sepages

### ISSUE THREAD

**Issue by capitainekurck** [lcapdecomme/vins#25]
je ne sais pas si c'est une limitation ou un bug

- quand on saisi les cépages même si pour le second cépage on passe a la ligne pour qu'il y ai un cépage par ligne lorsqu’on valide le second cépage il se retrouve a la suite du premier sur la première ligne séparé du précédent par une virgule. idem pour le 3 eme 4 eme ...

- si on saisie un cépage qui n'existe pas dans la base ensuite le chois n'est plus proposé pour les suivants. ça serai bien que le nouveau cépage s'ajoute a la base

**Comment by lcapdecomme** [comment]
Pour le pt 1, je vais voir si je peux améliorer ça.
Pour le point 2, je ne pense pas que ce soit pertinent que tout le monde puisse ajouter des cépages. S'il en manque, je préfère les ajouter et les livrer avec une mise à jour de la base.

**Comment by lcapdecomme** [comment]
Pourriez-vous me donner des exemples de cépages manquants ?
