### ISSUE TITLE
Ajout de photos

### ISSUE THREAD

**Issue by capitainekurck** [lcapdecomme/vins#32]
Bonjour
J'ai fait la mise a jour vers la V0.6 et j'ai quelques bugs
1 lorsqu'on ajoute une photo a un vin déjà existant  et qu'on valide avec le bouton modifier, la page devient blanche (pas le header) et rien ne se passe. dans la table le champ nomphoto reste a null 
2 lorsqu’on ajoute un nouveau vin avec photo l'ajout se passe correctement , il est bien créé mais pas de photo. dans la table le champ nomphoto reste a null 

il y a t'il un poids ou une taille max pour la photo ? se redimensionne t elle ?
ou doit elle se stocker ? (nom du répertoire )

**Comment by lcapdecomme** [comment]
Effectivement, j'ai oublié de livrer le nouveau répertoire uploads 
Pour corriger ce problème, créez un répertoire uploads à la racine de votre projet.

**Comment by capitainekurck** [comment]
j'ai tester la V0.61 mais c'est idem avec la V0.60 et créant manuellement le rep uploads, ca ne fonctionne toujours pas. la table sql n'est pas mise a jour et la photo n'est pas copier dans le rep upload

J'ai fait la manip manuellement c'est a dire copier une image dans le rep uploads et mettre le nom dans la table et la on a bien une icône photo en face du vin et si on clique dessus l’aperçu de la bouteille apparait bien

**Comment by lcapdecomme** [comment]
Est-ce que l'upload marche ?

**Comment by lcapdecomme** [comment]
Est-ce que vous pouvez essayer avec un autre navigateur ? Internet Explorer, Firefox ou chrome
Vous êtes sous Windows ou linux ? 
Et quelle version de PHP vous utilisez ?

**Comment by capitainekurck** [comment]
bonjour

j'ai essayé avec une version 42 de firefox et un ie 11 avec xp et seven. je ne suis pas sous linux en poste de travail . c'est juste mon serveur enfin mes serveurs virtualisés. 

le serveur web tourne sur une debian : Version PHP : 5.3.3-7+squeeze23 lts.

voila le message de debug:
Array ( [file] => Array ( [name] => IMG_8593.JPG [type] => image/jpeg [tmp_name] => /tmp/phpgMSy15 [error] => 0 [size] => 931279 ) ) Array ( [name] => IMG_8593.JPG [type] => image/jpeg [tmp_name] => /tmp/phpgMSy15 [error] => 0 [size] => 931279 ) name:IMG_8593.JPG
temp name:/tmp/phpgMSy15
error:0
size:931279
success:

**Comment by lcapdecomme** [comment]
Bonjour,
Tout semble bien se passer. Le fichier doit se trouver sur votre serveur linux dans le répertoire /tmp non ? 
Il y a peut-être un problème de droit sur votre répertoire uploads
Essayer de le changer via un chmod : sudo chmod 755 uploads
Et si cela ne fonctionne toujours pas, positionnez tous les droits  : sudo chmod 777 uploads

**Comment by capitainekurck** [comment]
bonjour 
en effet quand j’ai créé manuellement le rep uploads j'ai oublié de mettre les droits sur www-data et ils étaient sur root. maintenant ça fonctionne bien, mais il reste un petit bug l’extension de limage est tronqué
j'ai vu ça dans l'error log apachee  
[Wed Nov 30 19:28:48 2016] [error] [client X.X.X.X] PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phpYYlrDZ' to '/var/www/vins/uploads/**1-2-IMG_8590.J**' in /var/www/vins/maj_bouteille.php on line 99, referer: http://X.X.X.X/vins/maj_bouteille.php?id=2&debug

**Comment by lcapdecomme** [comment]
Warning: move_uploaded_file(): Unable to move ... Vous avez bien le fichier dans uploads ? 
Pour l'extension tronquée, j'ai corrigé ça il y a qques jours, ce sera livré dans la prochaine release.

**Comment by capitainekurck** [comment]
oui maintenant tout fonctionne correctement

**Comment by lcapdecomme** [comment]
Ok je ferme le ticket.
Je pense que le bug de l'image tronquée est corrigée sur la v0.7
