### ISSUE TITLE
quelques idées

### ISSUE THREAD

**Issue by capitainekurck** [lcapdecomme/vins#34]
C'est vraiment pas mal comme boulot.  en tout cas, fonctionnellement c'est assez complet pour gérer une cave . 
quelque idées en vrac:
- cliquer sur le non du vin pour accéder aux caractéristiques c'est peut être plus naturel que le bouton bleu.
- faire afficher la photo de la bouteille lors quelle existe en sur impression a gauche dans les caractéristiques du vin sur la photo du verre 'stylisé'.
- gérer 2 photos par bouteilles la photo d’elle même plus l’étiquette qu'il y a souvent derrière qui reprend les caractéristique du vin.
- imprimer des étiquettes avec les caractéristiques des bouteilles.
- gérer les emplacements des bouteilles dans les casiers en X et Y.

**Comment by lcapdecomme** [comment]
ok pour tout.
Le mieux pour moi est que vous proposiez  une idée par issue.
Cela permet de les planifier et d'en discuter si il y a des choses à dire ou des commentaires à faire.
