### ISSUE TITLE
quelques problemes qui me semble etre des bug.

### ISSUE THREAD

**Issue by capitainekurck** [lcapdecomme/vins#35]
chez moi la recherche sur le champ commentaire ne donne aucun résultats. la liste de tous les vins reste affichée sans que seul ceux qui correspondent aux critères de la recherche apparaissent.

le redimensionnement des colonnes est assez rock'n roll. quand on redimensionne plus d'une colonne les autres, placées sur sa gauche, semblent être liées par un facteur de pourcentage et se redimensionnent d’elle même , en général en se rapetissant.

**Comment by lcapdecomme** [comment]
Pour la recherche, c'était uniquement dans la zone commentaire. J'ai ajouté aussi dans le nom de la bouteille sachant que le filtre de cette colonne faisait déjà ça. Est-ce mieux ? 

Pour le redimensionnement des colonnes, c'est l'outil qui fait ça. Je ne crois pas avoir trop la main dessus.
