### ISSUE TITLE
bug V 0.7

### ISSUE THREAD

**Issue by capitainekurck** [lcapdecomme/vins#43]
je viens de migrer en v .7 et j'ai trouvé 2 bug ( mais ils étaient peut être déjà en V6)

- 1 les 2 photos ne sont que dans la mise a jour bouteille et pas dans la création d'une nouvelle bouteille. dans la nouvelle bouteille il y a toujours 1 seul bouton image.

- 2 J'ai créé un second utilisateur de test et lorsque je crer ou modifi une bouteille je n'ai pas le champ emplacement et X Y

**Comment by lcapdecomme** [comment]
Le point 1 sera corrigé dans le prochain correctif
Le point 2 vient probablement du fait qu'aucun emplacement n'a été paramétré pour cet utilisateur
